spring:
  redis:
      open: true  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 172.18.2.223
      port: 6379
      password: sj!@G)1D3_D&12      # 密码（默认为空）
      timeout: 6000  # 连接超时时长（毫秒）
      pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
netty:
  tcp:
    port: 7788
  boss:
    thread:
      count: 2
  worker:
    thread:
      count: 20
  so:
    keepalive: true
    backlog: 800
  msg:
    length: 2048
  bi:
    pool: 20
chisondo:
  iot:
    deviceHttpPort: 8099
    deviceTcpPort: 16888
chris:
  interface:
    url:
      appHttpURL: http://127.0.0.1:8086/